const response = {
  total_count: 2322,
  incomplete_results: false,
  items: [
    {
      login: 'example',
      id: 57936,
      node_id: 'MDQ6VXNlcjU3OTM2',
      avatar_url: 'https://avatars.githubusercontent.com/u/57936?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/example',
      html_url: 'https://github.com/example',
      followers_url: 'https://api.github.com/users/example/followers',
      following_url: 'https://api.github.com/users/example/following{/other_user}',
      gists_url: 'https://api.github.com/users/example/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/example/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/example/subscriptions',
      organizations_url: 'https://api.github.com/users/example/orgs',
      repos_url: 'https://api.github.com/users/example/repos',
      events_url: 'https://api.github.com/users/example/events{/privacy}',
      received_events_url: 'https://api.github.com/users/example/received_events',
      type: 'User',
      site_admin: false,
      score: 1.0,
    },
    {
      login: 'examplecode',
      id: 2177000,
      node_id: 'MDQ6VXNlcjIxNzcwMDA=',
      avatar_url: 'https://avatars.githubusercontent.com/u/2177000?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/examplecode',
      html_url: 'https://github.com/examplecode',
      followers_url: 'https://api.github.com/users/examplecode/followers',
      following_url: 'https://api.github.com/users/examplecode/following{/other_user}',
      gists_url: 'https://api.github.com/users/examplecode/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/examplecode/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/examplecode/subscriptions',
      organizations_url: 'https://api.github.com/users/examplecode/orgs',
      repos_url: 'https://api.github.com/users/examplecode/repos',
      events_url: 'https://api.github.com/users/examplecode/events{/privacy}',
      received_events_url: 'https://api.github.com/users/examplecode/received_events',
      type: 'User',
      site_admin: false,
      score: 1.0,
    },
    {
      login: 'infologs',
      id: 17062486,
      node_id: 'MDQ6VXNlcjE3MDYyNDg2',
      avatar_url: 'https://avatars.githubusercontent.com/u/17062486?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/infologs',
      html_url: 'https://github.com/infologs',
      followers_url: 'https://api.github.com/users/infologs/followers',
      following_url: 'https://api.github.com/users/infologs/following{/other_user}',
      gists_url: 'https://api.github.com/users/infologs/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/infologs/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/infologs/subscriptions',
      organizations_url: 'https://api.github.com/users/infologs/orgs',
      repos_url: 'https://api.github.com/users/infologs/repos',
      events_url: 'https://api.github.com/users/infologs/events{/privacy}',
      received_events_url: 'https://api.github.com/users/infologs/received_events',
      type: 'User',
      site_admin: false,
      score: 1.0,
    },
    {
      login: 'vipulnsward',
      id: 567626,
      node_id: 'MDQ6VXNlcjU2NzYyNg==',
      avatar_url: 'https://avatars.githubusercontent.com/u/567626?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/vipulnsward',
      html_url: 'https://github.com/vipulnsward',
      followers_url: 'https://api.github.com/users/vipulnsward/followers',
      following_url: 'https://api.github.com/users/vipulnsward/following{/other_user}',
      gists_url: 'https://api.github.com/users/vipulnsward/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/vipulnsward/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/vipulnsward/subscriptions',
      organizations_url: 'https://api.github.com/users/vipulnsward/orgs',
      repos_url: 'https://api.github.com/users/vipulnsward/repos',
      events_url: 'https://api.github.com/users/vipulnsward/events{/privacy}',
      received_events_url: 'https://api.github.com/users/vipulnsward/received_events',
      type: 'User',
      site_admin: false,
      score: 1.0,
    },
    {
      login: 'chilkatsoft',
      id: 16035810,
      node_id: 'MDQ6VXNlcjE2MDM1ODEw',
      avatar_url: 'https://avatars.githubusercontent.com/u/16035810?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/chilkatsoft',
      html_url: 'https://github.com/chilkatsoft',
      followers_url: 'https://api.github.com/users/chilkatsoft/followers',
      following_url: 'https://api.github.com/users/chilkatsoft/following{/other_user}',
      gists_url: 'https://api.github.com/users/chilkatsoft/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/chilkatsoft/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/chilkatsoft/subscriptions',
      organizations_url: 'https://api.github.com/users/chilkatsoft/orgs',
      repos_url: 'https://api.github.com/users/chilkatsoft/repos',
      events_url: 'https://api.github.com/users/chilkatsoft/events{/privacy}',
      received_events_url: 'https://api.github.com/users/chilkatsoft/received_events',
      type: 'User',
      site_admin: false,
      score: 1.0,
    },
  ],
};

const fakeInfo = [
  {
    "login": "BoxenOfDonuts",
    "id": 7082618,
    "node_id": "MDQ6VXNlcjcwODI2MTg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7082618?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/BoxenOfDonuts",
    "html_url": "https://github.com/BoxenOfDonuts",
    "followers_url": "https://api.github.com/users/BoxenOfDonuts/followers",
    "following_url": "https://api.github.com/users/BoxenOfDonuts/following{/other_user}",
    "gists_url": "https://api.github.com/users/BoxenOfDonuts/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/BoxenOfDonuts/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/BoxenOfDonuts/subscriptions",
    "organizations_url": "https://api.github.com/users/BoxenOfDonuts/orgs",
    "repos_url": "https://api.github.com/users/BoxenOfDonuts/repos",
    "events_url": "https://api.github.com/users/BoxenOfDonuts/events{/privacy}",
    "received_events_url": "https://api.github.com/users/BoxenOfDonuts/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "joelhacke.com",
    "location": 'Planet Earth',
    "email": 'joel.hacke@gmail.com',
    "hireable": null,
    "bio": 'Fake Bio info, just for testing. I love coffee and science fiction books',
    "twitter_username": null,
    "public_repos": 30,
    "public_gists": 0,
    "followers": 1,
    "following": 2,
    "created_at": "2014-03-27T15:05:47Z",
    "updated_at": "2021-04-17T22:05:10Z"
  }
]

export {response, fakeInfo};
